<?php
require_once 'includes\database.inc';
require_once 'includes\functions.inc';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Campus Inventory Assets</title>
</head>
<body>
    <div id="menu">
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="login.php">Login</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="contact.php">Contact us</a></li>
        </ul>
    </div>